### ISSUE TITLE
How to trigger this action rerun after fixing the PR title

### ISSUE THREAD

**Issue by lwshang** [aslafy-z/conventional-pr-title-action#165]
The PR was made with a title not matches the convention. So the action failed.

After changing the title, how can we rerun this action with the new title?

GitHub action provides the button to "Re-run all jobs", but the conventional-pr-title action still failed. It seems that the action still checks against the previous wrong title.

**Comment by tchalvak** [comment]
That is a good question, yeah.

**Comment by aslafy-z** [comment]
The workflow should be configured to get triggered by the `edited` event as seen [in the example](https://github.com/aslafy-z/conventional-pr-title-action#example-usage). Does it work for you?
