### ISSUE TITLE
How to indicate breaking change?

### ISSUE THREAD

**Issue by Andrew-Sheridan** [aslafy-z/conventional-pr-title-action#183]
I see this in the tests
```
    "fix: Fix bug\n\nBREAKING CHANGE: Fix bug",
```

But there is no way to have a multi line PR title, so no way to indicate a breaking change.. right?

**Comment by aslafy-z** [comment]
This depends on your preset. Some will use the commit content (it can be set on merge, but, yeah, validation will not be done by the plugin). Some other uses `!` like: `feat!: Introduce breaking change` or `BREAKING CHANGE: feat: Introduce blabla`.
Please check what format is supported by the preset you use

**Comment by Andrew-Sheridan** [comment]
Hi, thanks for responding.

We are exploring alternative presets now, thank you. 

While we are doing that, let me add a few more details.

For the action you have written, to lint our PR titles, we have been using the default preset, `conventional-changelog-angular`.

In [their documentation](https://github.com/conventional-changelog-archived-repos/conventional-changelog-angular/blob/master/convention.md) they show that breaking change is indicated by including `BREAKING CHANGE: ` in the footer.

The test that you have to see if you are correctly detecting valid titles uses the same format

```
fix: Fix bug\n\nBREAKING CHANGE: Fix bug
```
- https://github.com/aslafy-z/conventional-pr-title-action/blob/5b4c19b2defc19a9eb6e5b0451c6861d5e2a86d2/src/validateTitle.test.js#L14-L21) 

This is perfectly valid commit message - we have some exactly like that.

However, it does not appear to be a valid Pull Request title, because it contains two newline characters. Unless it _is_ possible to have a multiline PR title and I just don't know how?

With the default preset it does not appear possible to indicate a breaking change in a PR title. Is that correct?

Thank you again!

**Comment by Andrew-Sheridan** [comment]
Some testing:

Using the preset `cz-conventional-changelog` and the title `"feat!: test PR do not merge"` results in this great error message:

```text
2022-03-18T22:04:21.6637876Z ##[error]No release type found in pull request title "feat!: test PR do not merge".

Add a prefix like "fix: ", "feat: " or "feat!: " to indicate what kind of release this pull request corresponds to. The title should match the commit mesage format as specified by https://www.conventionalcommits.org/.
```

I tested the other example you suggested (`"BREAKING CHANGE: feat: test PR do not merge"` same result.

Trying with the default preset, `conventional-changelog-angular`, produces the same results.

**Comment by Andrew-Sheridan** [comment]
I got this working by using the preset `conventional-changelog-conventionalcommits@latest`

thank you!
