### ISSUE TITLE
"feat!:" prefix not supported

### ISSUE THREAD

**Issue by scjody** [aslafy-z/conventional-pr-title-action#236]
The "feat!:" prefix (feature with a breaking change) is not supported, despite being mentioned in the "No release type found" error message:

> Add a prefix like "fix: ", "feat: " or "feat!: " to indicate what kind of release this pull request corresponds to. The title should match the commit mesage format as specified by [https://www.conventionalcommits.org/.](https://www.conventionalcommits.org/)

https://github.com/aslafy-z/conventional-pr-title-action/pull/235 adds a failing test to illustrate this issue.

**Comment by aslafy-z** [comment]
It looks like the default preset [`angular`](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular) does not support this way of indicating a breaking change. Switching to [`conventionalcommits`](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits) by specifying `preset:  conventionalcommits` should do the trick. 
I will work on updating the default preset, the way they are loaded and some other things for this action in the coming days. Thank you for using it!

**Comment by aslafy-z** [comment]
With https://github.com/aslafy-z/conventional-pr-title-action/releases/tag/v3.0.0, this action now uses `conventional-changelog-conventionalcommits@5.0.0` as the default preset. It should then support your use case. 
I'll go ahead and close this issue, feel free to re-open it if you feel like it needs some more work.

**Comment by scjody** [comment]
We finally had the chance to test this and it works! Thanks for the fix!
