### ISSUE TITLE
The action fails to validate a commit message with prefix/type `feat!:`

### ISSUE THREAD

**Issue by TristanSpeakEasy** [aslafy-z/conventional-pr-title-action#251]
As can be seen in this action run here: https://github.com/speakeasy-api/speakeasy/actions/runs/3891915784/jobs/6642719562

The commit title is `feat!: add auth requirement to the CLI`

But the below error is returned:

```
Error: No release type found in pull request title "feat!: add auth requirement to the CLI".

Add a prefix like "fix: ", "feat: " or "feat!: " to indicate what kind of release this pull request corresponds to. The title should match the commit mesage format as specified by [https://www.conventionalcommits.org/.](https://www.conventionalcommits.org/)
```

It even gives an example of using `feat!:` in the error response

**Comment by TristanSpeakEasy** [comment]
Have just tracked down that this is due to the preset https://github.com/aslafy-z/conventional-pr-title-action/issues/236

I still think its a bug that the suggestion for fixing it is misleading

**Comment by aslafy-z** [comment]
@TristanSpeakEasy AFAIK, conventional-changelog `angular` preset does not support this way of expressing a breaking change where `conventionalcommits` supports them.

See https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-angular/parser-opts.js vs https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-conventionalcommits/parser-opts.js

Howerver, I agree that the message could be updated to be less specific and match a wider audience.
