### ISSUE TITLE
/bin/sh: 1: npm: not found

### ISSUE THREAD

**Issue by alfieyfc** [aslafy-z/conventional-pr-title-action#283]
Hello, thanks for this great action!

We've been using this for quite some time without any issues. Suddenly, since recent hours, we started to see this error:
<img width="600" alt="image" src="https://github.com/aslafy-z/conventional-pr-title-action/assets/41598103/c7589e29-50fd-4d05-ac01-2299d2635e4e">

```
Error: Command failed: npm install --quiet conventional-changelog-angular@latest
/bin/sh: 1: npm: not found
```

We suspect this may have to do with the latest release from #267. Was there anything intended for us to change on our side for using the latest release?

**Comment by JackRhodes** [comment]
I have hit the same issue!

I have mitigated by rolling back to the previous version

`- uses: actions/aslafy-z_conventional-pr-title-action@v3`

to

` - uses: actions/aslafy-z_conventional-pr-title-action@v3.0.1`


One thing to note to people doing this. If you are using the default action linked on the README, the the action will still be using the old one on the PR you create with this change. I had to bypass PR policies and merge this, it then fixed any open PR's I had.

It would be great if the breaking change @alfieyfc has highlighted could be reverted ASAP as this is highly disruptive to anyone pinning to `@3` and uses this action on many repos.

**Comment by aslafy-z** [comment]
Hey there! Sorry for the inconvenience. Can you please try again, branch v3 is updated with the reverted version.

@iamludal  In the current implementation, users can specify a package name for their conventionalcommits preset. This package will be installed with NPM if not present. The way this is done is not supported by your implementation at #267. Let's work a bit more on this before releasing in a new major.

**Comment by iamludal** [comment]
Hi! Sorry for the inconvenience. 

@aslafy-z Let's release a new major when the change will be stable as you suggested.

**Comment by aslafy-z** [comment]
The issue should be gone now, can you confirm @JackRhodes @alfieyfc? Thank you

**Comment by thiagownt** [comment]
Hi, I think you have deleted a release. I think it would be better if a new patch was released instead of removing the version. The new version was working on my repos and dependabot auto-merged the changes and now my workflows are broken because the release has been retracted.

**Comment by aslafy-z** [comment]
@thiagownt Noted. I re-created mirror tags of 3.0.1 as 3.1.0 and 3.1.1. I will make sure this does not happen again in the future. I will proceed and close this issue.

**Comment by thiagownt** [comment]
@aslafy-z thanks for that. It is all working now 💯
