### ISSUE TITLE
Unknown issue with preset

### ISSUE THREAD

**Issue by Tbhesswebber** [aslafy-z/conventional-pr-title-action#304]
This may be an issue with the preset itself rather than the consumption of it, but this [CI run](https://github.com/Tbhesswebber/eslint-config/pull/16) is failing when trying to use the "breaking" tag with the "eslint" preset.  In the [action run details](https://github.com/Tbhesswebber/eslint-config/actions/runs/6375798123/job/17301974040?pr=16) it says "Please use one of these recognized types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert.", which seems to indicate that the stated tags used by the preset aren't necessarily being recognized somehow.

I'd love to understand how to get around this and whether or not I should be raising an issue with the preset itself.

**Comment by aslafy-z** [comment]
This is an issue with the way this projects checks for allowed prefixes. Currently, it uses https://github.com/commitizen/conventional-commit-types/blob/master/index.json which is an hardcoded list. It's not possible to make them change.
I would advise you to migrate to https://github.com/amannn/action-semantic-pull-request which supports your use case.
