### ISSUE TITLE
Success Output is reversed

### ISSUE THREAD

**Issue by DanielHabenicht** [aslafy-z/conventional-pr-title-action#63]
The Success Output `success` is reversed. It returns `true` if the check failed and `false` if the check succeeded. 
![image](https://user-images.githubusercontent.com/13590797/96864439-b160d680-1468-11eb-8334-feb447803c1d.png)
![image](https://user-images.githubusercontent.com/13590797/96864523-d9e8d080-1468-11eb-9d1e-5555951ec3de.png)

**Comment by aslafy-z** [comment]
Thanks for reporting! Just fixed it with #65. I will be automatically released in no time.
