### ISSUE TITLE
Docker image is no longer available on DockerHub

### ISSUE THREAD

**Issue by mauricioklein** [aslafy-z/conventional-pr-title-action#80]
The library is using the Docker image "aslafy-z/conventional-pr-title-action", which is no longer available on DockerHub.

Would be possible to push the image again?

Thanks!

**Comment by aslafy-z** [comment]
This image is now automatically published to GHCR as you can see in the readme: https://github.com/aslafy-z/conventional-pr-title-action#example-usage
